// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.5
// source: proto/location.proto

package locationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LocationRequest carries a single GPS data point from a driver.
type LocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique UUID v4 generated by client for idempotency/tracking.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Stable driver identifier / code (e.g. "driver-001").
	DriverCode string `protobuf:"bytes,2,opt,name=driver_code,json=driverCode,proto3" json:"driver_code,omitempty"`
	// WGS-84 latitude in decimal degrees [-90, 90].
	Latitude float64 `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// WGS-84 longitude in decimal degrees [-180, 180].
	Longitude float64 `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Current speed in km/h.
	Speed float32 `protobuf:"fixed32,5,opt,name=speed,proto3" json:"speed,omitempty"`
	// Compass heading in degrees [0, 360), 0 = North, clockwise.
	Heading float32 `protobuf:"fixed32,6,opt,name=heading,proto3" json:"heading,omitempty"`
	// Timestamp when GPS fix was recorded.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationRequest) Reset() {
	*x = LocationRequest{}
	mi := &file_proto_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationRequest) ProtoMessage() {}

func (x *LocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationRequest.ProtoReflect.Descriptor instead.
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{0}
}

func (x *LocationRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LocationRequest) GetDriverCode() string {
	if x != nil {
		return x.DriverCode
	}
	return ""
}

func (x *LocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *LocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *LocationRequest) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *LocationRequest) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *LocationRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// LocationAck acknowledges receipt and processing result for a single LocationRequest.
type LocationAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches the event_id from the corresponding LocationRequest.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// True if accepted and queued for Kafka, false if rejected / backpressure.
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Informative message or rejection reason.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationAck) Reset() {
	*x = LocationAck{}
	mi := &file_proto_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationAck) ProtoMessage() {}

func (x *LocationAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationAck.ProtoReflect.Descriptor instead.
func (*LocationAck) Descriptor() ([]byte, []int) {
	return file_proto_location_proto_rawDescGZIP(), []int{1}
}

func (x *LocationAck) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LocationAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *LocationAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_location_proto protoreflect.FileDescriptor

const file_proto_location_proto_rawDesc = "" +
	"\n" +
	"\x14proto/location.proto\x12\blocation\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x01\n" +
	"\x0fLocationRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vdriver_code\x18\x02 \x01(\tR\n" +
	"driverCode\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x02R\x05speed\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x02R\aheading\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"^\n" +
	"\vLocationAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2Y\n" +
	"\x0fLocationService\x12F\n" +
	"\x0eStreamLocation\x12\x19.location.LocationRequest\x1a\x15.location.LocationAck(\x010\x01B4Z2github.com/Tento03/fleet-tracking/proto;locationpbb\x06proto3"

var (
	file_proto_location_proto_rawDescOnce sync.Once
	file_proto_location_proto_rawDescData []byte
)

func file_proto_location_proto_rawDescGZIP() []byte {
	file_proto_location_proto_rawDescOnce.Do(func() {
		file_proto_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_location_proto_rawDesc), len(file_proto_location_proto_rawDesc)))
	})
	return file_proto_location_proto_rawDescData
}

var file_proto_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_location_proto_goTypes = []any{
	(*LocationRequest)(nil),       // 0: location.LocationRequest
	(*LocationAck)(nil),           // 1: location.LocationAck
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_location_proto_depIdxs = []int32{
	2, // 0: location.LocationRequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: location.LocationService.StreamLocation:input_type -> location.LocationRequest
	1, // 2: location.LocationService.StreamLocation:output_type -> location.LocationAck
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_location_proto_init() }
func file_proto_location_proto_init() {
	if File_proto_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_location_proto_rawDesc), len(file_proto_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_location_proto_goTypes,
		DependencyIndexes: file_proto_location_proto_depIdxs,
		MessageInfos:      file_proto_location_proto_msgTypes,
	}.Build()
	File_proto_location_proto = out.File
	file_proto_location_proto_goTypes = nil
	file_proto_location_proto_depIdxs = nil
}
